{
  "hash": "1170509447509229db07a88dee91b2dd",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-Home Exercise 1\"\nauthor: \"Amelia Rosalind\"\ndate: \"May 22, 2026\"\ndate-modified: \"last-modified\"\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n---\n\n# Getting Started\n\n## Installing of required packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(corrplot, ggstatsplot, tidyverse, knitr)\n```\n:::\n\n\n## Importing data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance <- read_csv2(\"Motor_insurance.csv\")\n```\n:::\n\n\n# Checking Dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(insurance)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 354,140\nColumns: 47\n$ insured_id                  <dbl> 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, …\n$ year                        <dbl> 2022, 2022, 2023, 2024, 2022, 2023, 2024, …\n$ policy_type                 <chr> \"COMP_E\", \"COMP_E\", \"COMP_E\", \"COMP_E\", \"C…\n$ policy_status               <chr> \"C\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A…\n$ business_type               <chr> \"NB\", \"P\", \"P\", \"P\", \"NB\", \"P\", \"P\", \"NB\",…\n$ payment_frequency           <chr> \"A\", \"A\", \"A\", \"A\", \"S\", \"S\", \"S\", \"A\", \"A…\n$ bonus_score                 <chr> \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G…\n$ driver_age                  <dbl> 48, 43, 44, 45, 45, 46, 47, 32, 33, 34, 39…\n$ vehicle_age                 <dbl> 22, 24, 25, 26, 26, 27, 28, 12, 13, 14, 20…\n$ age_driving_licence         <dbl> 26, 19, 19, 18, 19, 19, 19, 19, 19, 19, 19…\n$ fuel_type                   <chr> \"G\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D…\n$ vehicle_value               <dbl> 1495114425, 650651232, 650651232, 65065123…\n$ seats                       <dbl> 4, 8, 8, 8, 7, 7, 7, 5, 5, 5, 5, 5, 5, 5, …\n$ power_to_weight_ratio       <dbl> 392, 1015, 1015, 1015, 919, 919, 919, 117,…\n$ vehicle_brand               <chr> \"PORSCHE\", \"MERCEDES\", \"MERCEDES\", \"MERCED…\n$ municipality_type           <chr> \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I…\n$ circulation_area            <chr> \"U\", \"U\", \"U\", \"U\", \"R\", \"R\", \"R\", \"R\", \"R…\n$ total_premium               <dbl> 2.795576e+14, 5.466234e+14, 5.487526e+14, …\n$ liability_premium           <chr> \"30.6023237556165\", \"114.333356153425\", \"1…\n$ property_damage_premium     <chr> \"121.912689768658\", \"303.105967487671\", \"3…\n$ theft_premium               <chr> \"112.361488722247\", \"80.784823960274\", \"83…\n$ fire_premium                <chr> \"3.83244054509589\", \"7.82686089041096\", \"6…\n$ glass_premium               <chr> \"8.30578787063014\", \"30.091750730137\", \"32…\n$ legal_protection_premium    <chr> \"2.04362162038356\", \"7.81274746849314\", \"7…\n$ occupants_premium           <chr> \"0.499205281315068\", \"2.66790841643835\", \"…\n$ total_claims                <dbl> 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ liability_claims            <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_property_claims   <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_injury_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ property_claims             <dbl> 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ theft_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_claims                 <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_claims            <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_incurred              <dbl> 0, 0, 233013, 25863615, 0, 0, 0, 0, 0, 0, …\n$ liability_incurred          <dbl> 0, 0, 233013, 1035, 0, 0, 0, 0, 0, 0, 0, 0…\n$ liability_property_incurred <dbl> 0, 0, 233013, 1035, 0, 0, 0, 0, 0, 0, 0, 0…\n$ liability_injury_incurred   <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ property_incurred           <dbl> 0, 0, 0, 15513615, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ theft_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_incurred               <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_incurred   <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_incurred          <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_exposure              <chr> \"0.0986301369863014\", \"1\", \"1\", \"1\", \"1\", …\n$ liability_exposure          <chr> \"0.0986301369863014\", \"1\", \"1\", \"1\", \"1\", …\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(insurance)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   insured_id          year      policy_type        policy_status     \n Min.   :     1   Min.   :2022   Length:354140      Length:354140     \n 1st Qu.: 33342   1st Qu.:2023   Class :character   Class :character  \n Median : 66840   Median :2023   Mode  :character   Mode  :character  \n Mean   : 76045   Mean   :2023                                        \n 3rd Qu.:112949   3rd Qu.:2024                                        \n Max.   :185678   Max.   :2024                                        \n                                                                      \n business_type      payment_frequency  bonus_score          driver_age   \n Length:354140      Length:354140      Length:354140      Min.   :18.00  \n Class :character   Class :character   Class :character   1st Qu.:39.00  \n Mode  :character   Mode  :character   Mode  :character   Median :48.00  \n                                                          Mean   :49.01  \n                                                          3rd Qu.:58.00  \n                                                          Max.   :90.00  \n                                                                         \n  vehicle_age    age_driving_licence  fuel_type         vehicle_value      \n Min.   : 0.00   Min.   : 0.00       Length:354140      Min.   :8.694e+03  \n 1st Qu.:17.00   1st Qu.:19.00       Class :character   1st Qu.:2.717e+06  \n Median :25.00   Median :20.00       Mode  :character   Median :2.617e+07  \n Mean   :25.92   Mean   :22.99                          Mean   :3.461e+09  \n 3rd Qu.:35.00   3rd Qu.:25.00                          3rd Qu.:2.608e+08  \n Max.   :68.00   Max.   :80.00                          Max.   :2.716e+11  \n NA's   :2       NA's   :2                              NA's   :513        \n     seats       power_to_weight_ratio vehicle_brand      municipality_type \n Min.   :2.000   Min.   :   0          Length:354140      Length:354140     \n 1st Qu.:5.000   1st Qu.: 898          Class :character   Class :character  \n Median :5.000   Median :1143          Mode  :character   Mode  :character  \n Mean   :5.084   Mean   :1008                                               \n 3rd Qu.:5.000   3rd Qu.:1333                                               \n Max.   :9.000   Max.   :6481                                               \n                                                                            \n circulation_area   total_premium       liability_premium \n Length:354140      Min.   :0.000e+00   Length:354140     \n Class :character   1st Qu.:1.708e+14   Class :character  \n Mode  :character   Median :2.791e+14   Mode  :character  \n                    Mean   :3.258e+14                     \n                    3rd Qu.:4.345e+14                     \n                    Max.   :1.000e+15                     \n                                                          \n property_damage_premium theft_premium      fire_premium      \n Length:354140           Length:354140      Length:354140     \n Class :character        Class :character   Class :character  \n Mode  :character        Mode  :character   Mode  :character  \n                                                              \n                                                              \n                                                              \n                                                              \n glass_premium      legal_protection_premium occupants_premium \n Length:354140      Length:354140            Length:354140     \n Class :character   Class :character         Class :character  \n Mode  :character   Mode  :character         Mode  :character  \n                                                               \n                                                               \n                                                               \n                                                               \n  total_claims     liability_claims liability_property_claims\n Min.   : 0.0000   Min.   :0.0000   Min.   :0.00000          \n 1st Qu.: 0.0000   1st Qu.:0.0000   1st Qu.:0.00000          \n Median : 0.0000   Median :0.0000   Median :0.00000          \n Mean   : 0.2177   Mean   :0.1066   Mean   :0.09281          \n 3rd Qu.: 0.0000   3rd Qu.:0.0000   3rd Qu.:0.00000          \n Max.   :18.0000   Max.   :8.0000   Max.   :8.00000          \n                                                             \n liability_injury_claims property_claims     theft_claims     \n Min.   :0.00000         Min.   : 0.00000   Min.   :0.000000  \n 1st Qu.:0.00000         1st Qu.: 0.00000   1st Qu.:0.000000  \n Median :0.00000         Median : 0.00000   Median :0.000000  \n Mean   :0.01376         Mean   : 0.06295   Mean   :0.005326  \n 3rd Qu.:0.00000         3rd Qu.: 0.00000   3rd Qu.:0.000000  \n Max.   :3.00000         Max.   :15.00000   Max.   :2.000000  \n                                                              \n  fire_claims         glass_claims     legal_protection_claims\n Min.   :0.0000000   Min.   :0.00000   Min.   :0.000000       \n 1st Qu.:0.0000000   1st Qu.:0.00000   1st Qu.:0.000000       \n Median :0.0000000   Median :0.00000   Median :0.000000       \n Mean   :0.0002824   Mean   :0.03271   Mean   :0.009753       \n 3rd Qu.:0.0000000   3rd Qu.:0.00000   3rd Qu.:0.000000       \n Max.   :1.0000000   Max.   :3.00000   Max.   :2.000000       \n                                                              \n occupants_claims    total_incurred      liability_incurred \n Min.   :0.0000000   Min.   :0.000e+00   Min.   :0.000e+00  \n 1st Qu.:0.0000000   1st Qu.:0.000e+00   1st Qu.:0.000e+00  \n Median :0.0000000   Median :0.000e+00   Median :0.000e+00  \n Mean   :0.0001214   Mean   :2.480e+11   Mean   :1.862e+11  \n 3rd Qu.:0.0000000   3rd Qu.:0.000e+00   3rd Qu.:0.000e+00  \n Max.   :1.0000000   Max.   :9.993e+14   Max.   :9.993e+14  \n                                                            \n liability_property_incurred liability_injury_incurred property_incurred  \n Min.   :0.000e+00           Min.   :0.000e+00         Min.   :0.000e+00  \n 1st Qu.:0.000e+00           1st Qu.:0.000e+00         1st Qu.:0.000e+00  \n Median :0.000e+00           Median :0.000e+00         Median :0.000e+00  \n Mean   :2.280e+11           Mean   :3.251e+08         Mean   :4.087e+10  \n 3rd Qu.:0.000e+00           3rd Qu.:0.000e+00         3rd Qu.:0.000e+00  \n Max.   :9.993e+14           Max.   :1.150e+14         Max.   :9.776e+14  \n                                                                          \n theft_incurred      fire_incurred       glass_incurred     \n Min.   :        0   Min.   :0.000e+00   Min.   :0.000e+00  \n 1st Qu.:        0   1st Qu.:0.000e+00   1st Qu.:0.000e+00  \n Median :        0   Median :0.000e+00   Median :0.000e+00  \n Mean   :    25329   Mean   :1.884e-02   Mean   :3.248e+08  \n 3rd Qu.:        0   3rd Qu.:0.000e+00   3rd Qu.:0.000e+00  \n Max.   :270698845   Max.   :2.829e+03   Max.   :1.150e+14  \n                     NA's   :94                             \n legal_protection_incurred occupants_incurred total_exposure    \n Min.   :0.000e+00         Min.   :0.00e+00   Length:354140     \n 1st Qu.:0.000e+00         1st Qu.:0.00e+00   Class :character  \n Median :0.000e+00         Median :0.00e+00   Mode  :character  \n Mean   :8.582e+10         Mean   :8.37e-01                     \n 3rd Qu.:0.000e+00         3rd Qu.:0.00e+00                     \n Max.   :9.933e+14         Max.   :6.90e+04                     \n                           NA's   :25                           \n liability_exposure\n Length:354140     \n Class :character  \n Mode  :character  \n                   \n                   \n                   \n                   \n```\n\n\n:::\n\n```{.r .cell-code}\ncolSums(is.na(insurance))[colSums(is.na(insurance)) > 0]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        vehicle_age age_driving_licence           fuel_type       vehicle_value \n                  2                   2                1287                 513 \n      fire_incurred  occupants_incurred \n                 94                  25 \n```\n\n\n:::\n\n```{.r .cell-code}\nkable(head(insurance))\n```\n\n::: {.cell-output-display}\n\n\n| insured_id| year|policy_type |policy_status |business_type |payment_frequency |bonus_score | driver_age| vehicle_age| age_driving_licence|fuel_type | vehicle_value| seats| power_to_weight_ratio|vehicle_brand |municipality_type |circulation_area | total_premium|liability_premium |property_damage_premium |theft_premium    |fire_premium     |glass_premium    |legal_protection_premium |occupants_premium | total_claims| liability_claims| liability_property_claims| liability_injury_claims| property_claims| theft_claims| fire_claims| glass_claims| legal_protection_claims| occupants_claims| total_incurred| liability_incurred| liability_property_incurred| liability_injury_incurred| property_incurred| theft_incurred| fire_incurred| glass_incurred| legal_protection_incurred| occupants_incurred|total_exposure     |liability_exposure |\n|----------:|----:|:-----------|:-------------|:-------------|:-----------------|:-----------|----------:|-----------:|-------------------:|:---------|-------------:|-----:|---------------------:|:-------------|:-----------------|:----------------|-------------:|:-----------------|:-----------------------|:----------------|:----------------|:----------------|:------------------------|:-----------------|------------:|----------------:|-------------------------:|-----------------------:|---------------:|------------:|-----------:|------------:|-----------------------:|----------------:|--------------:|------------------:|---------------------------:|-------------------------:|-----------------:|--------------:|-------------:|--------------:|-------------------------:|------------------:|:------------------|:------------------|\n|          1| 2022|COMP_E      |C             |NB            |A                 |G           |         48|          22|                  26|G         |    1495114425|     4|                   392|PORSCHE       |I                 |U                |  2.795576e+14|30.6023237556165  |121.912689768658        |112.361488722247 |3.83244054509589 |8.30578787063014 |2.04362162038356         |0.499205281315068 |            0|                0|                         0|                       0|               0|            0|           0|            0|                       0|                0|              0|                  0|                           0|                         0|                 0|              0|             0|              0|                         0|                  0|0.0986301369863014 |0.0986301369863014 |\n|          2| 2022|COMP_E      |A             |P             |A                 |G           |         43|          24|                  19|D         |     650651232|     8|                  1015|MERCEDES      |I                 |U                |  5.466234e+14|114.333356153425  |303.105967487671        |80.784823960274  |7.82686089041096 |30.091750730137  |7.81274746849314         |2.66790841643835  |            0|                0|                         0|                       0|               0|            0|           0|            0|                       0|                0|              0|                  0|                           0|                         0|                 0|              0|             0|              0|                         0|                  0|1                  |1                  |\n|          2| 2023|COMP_E      |A             |P             |A                 |G           |         44|          25|                  19|D         |     650651232|     8|                  1015|MERCEDES      |I                 |U                |  5.487526e+14|110.666890520548  |304.955989890411        |83.5213843561644 |6.15146490410959 |32.8616260273972 |7.6556365479452          |2.9395658630137   |            1|                1|                         1|                       0|               0|            0|           0|            0|                       0|                0|         233013|             233013|                      233013|                         0|                 0|              0|             0|              0|                         0|                  0|1                  |1                  |\n|          2| 2024|COMP_E      |A             |P             |A                 |G           |         45|          26|                  18|D         |     650651232|     8|                  1015|MERCEDES      |I                 |U                |  5.846324e+14|122.092532497808  |305.225092603562        |107.886871891233 |5.84289244602741 |31.1015839652054 |10.0841734339726         |2.39928272958904  |            2|                1|                         1|                       0|               1|            0|           0|            0|                       0|                0|       25863615|               1035|                        1035|                         0|          15513615|              0|             0|              0|                         0|                  0|1                  |1                  |\n|          3| 2022|COMP_E      |A             |NB            |S                 |G           |         45|          26|                  19|D         |     516266625|     7|                   919|KIA           |I                 |R                |  6.874905e+14|214.583989098871  |354.87413971463         |53.077620195781  |7.71576481002738 |48.5742976882192 |6.70070054334247         |1.96399548026301  |            0|                0|                         0|                       0|               0|            0|           0|            0|                       0|                0|              0|                  0|                           0|                         0|                 0|              0|             0|              0|                         0|                  0|1                  |1                  |\n|          3| 2023|COMP_E      |A             |P             |S                 |G           |         46|          27|                  19|D         |     516266625|     7|                   919|KIA           |I                 |R                |  6.936705e+14|207.141298737699  |393.289489861972        |35.4689559170959 |7.2754904079452  |42.7005231749589 |6.04677121249316         |1.74793864043836  |            0|                0|                         0|                       0|               0|            0|           0|            0|                       0|                0|              0|                  0|                           0|                         0|                 0|              0|             0|              0|                         0|                  0|1                  |1                  |\n\n\n:::\n:::\n\n\n## Problems\n\n1.  Some features have incorrect data type: liability_premium, property_damage_premium, theft_premium, fire_premium, glass_premium, legal_protection_premium, occupants_premium, total_exposure and liability_exposure. It should be numeric but registered as characters.\n\n2.  Some features have nulls: vehicle_value has 513 NAs, fuel_type has 1287 NAs, fire_incurred has 94 NAs, occupants_incurred has 25 NAs.\n\n3. Categoricals (policy_type, policy_status, business_type, payment_frequency, bonus_score, fuel_type, municipality_type, circulation_area) are stored as characters <chr> instead of factors <fct>. With data type factors, R will understand that it is categoricals and not some string. \n\n# Data Wragling\n\n## Cleaning the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance <- insurance %>%\n  # Fix columns with wrong data types\n  mutate(across(c(liability_premium, property_damage_premium, theft_premium,\n                  fire_premium, glass_premium, legal_protection_premium,\n                  occupants_premium, total_exposure, liability_exposure),\n                ~ as.numeric(gsub(\",\", \".\", .)))) %>%\n  # Convert categoricals to factors\n  mutate(across(c(policy_type, policy_status, business_type, payment_frequency,\n                  bonus_score, fuel_type, municipality_type, circulation_area),\n                as.factor))  %>%\n  drop_na()\n\nglimpse(insurance)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 352,219\nColumns: 47\n$ insured_id                  <dbl> 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, …\n$ year                        <dbl> 2022, 2022, 2023, 2024, 2022, 2023, 2024, …\n$ policy_type                 <fct> COMP_E, COMP_E, COMP_E, COMP_E, COMP_E, CO…\n$ policy_status               <fct> C, A, A, A, A, A, A, A, A, A, A, A, A, A, …\n$ business_type               <fct> NB, P, P, P, NB, P, P, NB, P, P, NB, P, P,…\n$ payment_frequency           <fct> A, A, A, A, S, S, S, A, A, A, A, A, A, A, …\n$ bonus_score                 <fct> G, G, G, G, G, G, G, G, G, G, G, G, G, G, …\n$ driver_age                  <dbl> 48, 43, 44, 45, 45, 46, 47, 32, 33, 34, 39…\n$ vehicle_age                 <dbl> 22, 24, 25, 26, 26, 27, 28, 12, 13, 14, 20…\n$ age_driving_licence         <dbl> 26, 19, 19, 18, 19, 19, 19, 19, 19, 19, 19…\n$ fuel_type                   <fct> G, D, D, D, D, D, D, D, D, D, D, D, D, D, …\n$ vehicle_value               <dbl> 1495114425, 650651232, 650651232, 65065123…\n$ seats                       <dbl> 4, 8, 8, 8, 7, 7, 7, 5, 5, 5, 5, 5, 5, 5, …\n$ power_to_weight_ratio       <dbl> 392, 1015, 1015, 1015, 919, 919, 919, 117,…\n$ vehicle_brand               <chr> \"PORSCHE\", \"MERCEDES\", \"MERCEDES\", \"MERCED…\n$ municipality_type           <fct> I, I, I, I, I, I, I, I, I, I, C, I, I, C, …\n$ circulation_area            <fct> U, U, U, U, R, R, R, R, R, R, R, U, U, R, …\n$ total_premium               <dbl> 2.795576e+14, 5.466234e+14, 5.487526e+14, …\n$ liability_premium           <dbl> 30.60232, 114.33336, 110.66689, 122.09253,…\n$ property_damage_premium     <dbl> 121.9127, 303.1060, 304.9560, 305.2251, 35…\n$ theft_premium               <dbl> 112.361489, 80.784824, 83.521384, 107.8868…\n$ fire_premium                <dbl> 3.832441, 7.826861, 6.151465, 5.842892, 7.…\n$ glass_premium               <dbl> 8.305788, 30.091751, 32.861626, 31.101584,…\n$ legal_protection_premium    <dbl> 2.043622, 7.812747, 7.655637, 10.084173, 6…\n$ occupants_premium           <dbl> 0.4992053, 2.6679084, 2.9395659, 2.3992827…\n$ total_claims                <dbl> 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ liability_claims            <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_property_claims   <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_injury_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ property_claims             <dbl> 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ theft_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_claims                 <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_claims            <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_incurred              <dbl> 0, 0, 233013, 25863615, 0, 0, 0, 0, 0, 0, …\n$ liability_incurred          <dbl> 0, 0, 233013, 1035, 0, 0, 0, 0, 0, 0, 0, 0…\n$ liability_property_incurred <dbl> 0, 0, 233013, 1035, 0, 0, 0, 0, 0, 0, 0, 0…\n$ liability_injury_incurred   <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ property_incurred           <dbl> 0, 0, 0, 15513615, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ theft_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_incurred               <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_incurred   <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_incurred          <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_exposure              <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n$ liability_exposure          <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n```\n\n\n:::\n\n```{.r .cell-code}\ncolSums(is.na(insurance))[colSums(is.na(insurance)) > 0]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnamed numeric(0)\n```\n\n\n:::\n:::\n\n\n## Feature Engineering\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance %>%\n  filter(age_driving_licence == 80) %>%\n  select(driver_age, age_driving_licence, year)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  driver_age age_driving_licence  year\n       <dbl>               <dbl> <dbl>\n1         82                  80  2024\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance <- insurance %>%\n  mutate(driving_experience = \n           driver_age - age_driving_licence)\n```\n:::\n\n\n## Check final data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(head(insurance))\n```\n\n::: {.cell-output-display}\n\n\n| insured_id| year|policy_type |policy_status |business_type |payment_frequency |bonus_score | driver_age| vehicle_age| age_driving_licence|fuel_type | vehicle_value| seats| power_to_weight_ratio|vehicle_brand |municipality_type |circulation_area | total_premium| liability_premium| property_damage_premium| theft_premium| fire_premium| glass_premium| legal_protection_premium| occupants_premium| total_claims| liability_claims| liability_property_claims| liability_injury_claims| property_claims| theft_claims| fire_claims| glass_claims| legal_protection_claims| occupants_claims| total_incurred| liability_incurred| liability_property_incurred| liability_injury_incurred| property_incurred| theft_incurred| fire_incurred| glass_incurred| legal_protection_incurred| occupants_incurred| total_exposure| liability_exposure| driving_experience|\n|----------:|----:|:-----------|:-------------|:-------------|:-----------------|:-----------|----------:|-----------:|-------------------:|:---------|-------------:|-----:|---------------------:|:-------------|:-----------------|:----------------|-------------:|-----------------:|-----------------------:|-------------:|------------:|-------------:|------------------------:|-----------------:|------------:|----------------:|-------------------------:|-----------------------:|---------------:|------------:|-----------:|------------:|-----------------------:|----------------:|--------------:|------------------:|---------------------------:|-------------------------:|-----------------:|--------------:|-------------:|--------------:|-------------------------:|------------------:|--------------:|------------------:|------------------:|\n|          1| 2022|COMP_E      |C             |NB            |A                 |G           |         48|          22|                  26|G         |    1495114425|     4|                   392|PORSCHE       |I                 |U                |  2.795576e+14|          30.60232|                121.9127|     112.36149|     3.832441|      8.305788|                 2.043622|         0.4992053|            0|                0|                         0|                       0|               0|            0|           0|            0|                       0|                0|              0|                  0|                           0|                         0|                 0|              0|             0|              0|                         0|                  0|      0.0986301|          0.0986301|                 22|\n|          2| 2022|COMP_E      |A             |P             |A                 |G           |         43|          24|                  19|D         |     650651232|     8|                  1015|MERCEDES      |I                 |U                |  5.466234e+14|         114.33336|                303.1060|      80.78482|     7.826861|     30.091751|                 7.812748|         2.6679084|            0|                0|                         0|                       0|               0|            0|           0|            0|                       0|                0|              0|                  0|                           0|                         0|                 0|              0|             0|              0|                         0|                  0|      1.0000000|          1.0000000|                 24|\n|          2| 2023|COMP_E      |A             |P             |A                 |G           |         44|          25|                  19|D         |     650651232|     8|                  1015|MERCEDES      |I                 |U                |  5.487526e+14|         110.66689|                304.9560|      83.52138|     6.151465|     32.861626|                 7.655636|         2.9395659|            1|                1|                         1|                       0|               0|            0|           0|            0|                       0|                0|         233013|             233013|                      233013|                         0|                 0|              0|             0|              0|                         0|                  0|      1.0000000|          1.0000000|                 25|\n|          2| 2024|COMP_E      |A             |P             |A                 |G           |         45|          26|                  18|D         |     650651232|     8|                  1015|MERCEDES      |I                 |U                |  5.846324e+14|         122.09253|                305.2251|     107.88687|     5.842892|     31.101584|                10.084173|         2.3992827|            2|                1|                         1|                       0|               1|            0|           0|            0|                       0|                0|       25863615|               1035|                        1035|                         0|          15513615|              0|             0|              0|                         0|                  0|      1.0000000|          1.0000000|                 27|\n|          3| 2022|COMP_E      |A             |NB            |S                 |G           |         45|          26|                  19|D         |     516266625|     7|                   919|KIA           |I                 |R                |  6.874905e+14|         214.58399|                354.8741|      53.07762|     7.715765|     48.574298|                 6.700700|         1.9639955|            0|                0|                         0|                       0|               0|            0|           0|            0|                       0|                0|              0|                  0|                           0|                         0|                 0|              0|             0|              0|                         0|                  0|      1.0000000|          1.0000000|                 26|\n|          3| 2023|COMP_E      |A             |P             |S                 |G           |         46|          27|                  19|D         |     516266625|     7|                   919|KIA           |I                 |R                |  6.936705e+14|         207.14130|                393.2895|      35.46896|     7.275490|     42.700523|                 6.046771|         1.7479386|            0|                0|                         0|                       0|               0|            0|           0|            0|                       0|                0|              0|                  0|                           0|                         0|                 0|              0|             0|              0|                         0|                  0|      1.0000000|          1.0000000|                 27|\n\n\n:::\n:::\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}